services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sd-rabbitmq
    hostname: sd-rabbitmq
    ports:
      - "5672:5672"
      # painel web: http://localhost:15672
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-dados:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  rabbitmq-dados:
